# aloo gobi

<p align="right">2.6.2018</p>

<h1 align="center">aloo gobi</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>

### ingredients
- 1 head cauliflower; cut into big size florets
- 1-2 russet potato, about 1 lb; large dice
- 1-2 Tbsp neutral oil
- 1" ginger root; peeled and minced
- 1 serrano; small dice, deseeded if preferred
- 3-4 on the vine tomatoes; diced
- 1 cup green peas
- 1 tsp ground cumin
- 1 tsp garam masala
- 2 tsp coriander
- 1/2 tsp turmeric 
- 1/4 tsp cayenne
- 1/2 bunch cilantro; rinsed, rough chop
- 1 lemon (optional)
- 1 recipe; perfect basmati

### instructions
1. Preheat the oven to 400°F. Toss cauliflower florets and potatoes with a couple tbsp neutral oil. Spread on baking sheet. 
Roast until caramelized and mostly tender, 20-30 minutes, tossing halfway through.
1. Heat a couple tbsp neutral oil in small stainless-steel skillet until shimmering. Add ginger and serrano chilis and 
cook, stirring frequently, until fragrant. About 1 minute. Add cumin, garam masala, coriander, turmeric, cayenne, and 
pinch of salt. Allow spices to toast in oil, being careful not to burn, for about one minute. Add 
roasted cauliflower and potato and toss well in spices. Cook for an additional 2 minutes, then add tomatoes. Cook until 
thickened and fragrant, about 5 minutes more. 
1. Add green peas and cook until warmed through - test some to make sure they're good. 
Adjust seasoning to taste with salt, lemon and additional garam masala or cayenne.
1. Stir in cilantro and serve with rice, passing lemon wedges tableside.

### notes
Would work well with roti or naan too.  Check out steamed basmati recipe.
