<p align="right">7.11.2019</p>

<h1 align="center">pasta e ceci (pasta and chickpea soup)</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>

### ingredients
- 3 Tbsp olive oil
- 2 stalks celery; roughly chopped
- 1 carrot; roughly chopped
- 1 yellow onion; roughly chopped
- 3 sprigs rosemary; minced
- 6 cups vegetable stock (I prefer better than bouillon)
- 1 15 oz cans chickpeas; drained and rinsed
- 8 oz. small pasta (cavatelli, ditalini or oriechette) 
- kosher salt and freshly ground black pepper, to taste
- 2 Tbsp parsley; minced
- parmesan cheese for serving
- lemon (optional)

### instructions
1. Heat oil in a 6-qt. saucepan over medium-high; add rosemary, celery, carrot, and onion and cook until soft, 8-10 minutes. 
1. Add stock and chickpeas; simmer 5 minutes. Remove half the chickpeas and purée until smooth; return chickpeas to pan. 
1. Add pasta and cook until al dente, 10 minutes; season with salt and pepper. Taste for acid and add lemon juice if needed.
1. Stir in parsley and serve with parmesan cheese.

### notes
Doubles well.  If you don't have fresh rosemary, do not add dried.  Alternatively, consider adding fresh thyme.

