# shakshuka

<p align="right">12.31.2017</p>

<h1 align="center">shakshuka</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a> | 
</div>
<br>

### ingredients
- 1 medium onion; small dice
- 4 cloves garlic; crushed then sliced
- 2 Anaheim peppers; seeds removed and diced
- 3 jalapeño or 2 serrano peppers; sliced
- 1 Tbsp cumin
- 2 tsp smoked paprika
- 28oz san marzano tomatoes
- 6 or 7 eggs
- 1 handful of chopped parsley
- 1/4 cup crumbled feta
- olive oil and pepper to finsih

### instructions
1. Heat a 12-14" pan on medium heat. Add onions, peppers, a few tablespoons of olive oil and a small pinch of salt and 
cook until onions are translucent and just beginning to brown. 
1. Add the garlic and cook for 30 seconds. Add the cumin and smoked paprika and cook for 30 more. Dump in the tomatoes
and crush with a wooden spoon until it resembles a chunky pasta sauce. Bring to a boil then reduce to low and simmer 
for approximately 15 minutes, stirring occasionally to prevent the sauce from burning at the bottom, until it is the 
consistency of oatmeal. 
1. This is a good time to taste the sauce and season it until it's right. 
1. Create egg divots with the back of a spoon and distribute the eggs into the divots. Spoon the sauce over some of the 
egg white before covering. Cook for 5-10 minutes checking for the eggs to be completely cooked like it is poached. 
1. Once the eggs are just about cooked, remove from heat and sprinkle with feta and parsley, a light drizzle of a good 
olive and a few cracks of pepper.

### notes
Goes well with baguette or naan.  Can add lots of different veggies to the base: carrots, radishes, green beans, 
eggplant, etc. Also goes well with a drizzle of tahini sauce.



