# steamed basmati rice

<p align="right">2.9.2018</p>

<h1 align="center">steamed basmati rice</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>

### ingredients
- 1 cup basmati rice
- 1.5 cups just boiled water
- 1-2 Tbsp neutral oil
- 1 pinch salt (3/4 tsp salt)
- spices: cloves, cinnamon stick, black peppercorns, cumin seeds, mustard seeds, curry leaves (all optional)

### instructions
1. Rinse rice under cold water a few times or until it runs clear.  Cover in cold water and let sit for at 
least 20 minutes, ideally 40 minutes, up to one hour.
1. Heat oil in a broad pan (at least 12-14").  If using spices, add to the hot oil and fry until fragrant. 
1. Add drained rice and the salt and toss to coat.  Dump in just boiling water and bring pan to an aggresive boil.
1. Once boiling, cover, turn heat down to low and let cook for 10 minutes.
1. Keeping top on, remove from heat and let steam in residual heat for another 10 minutes.
1. Serve with tasty curries.

### notes
Some combinations of aromatics I enjoy are a cinnamon stick and cloves, or cumin or mustard seeds and curry leaves. 
Can be scaled 100% when doubling, but reduce to 2.5 cups boiling water. 
