# food processor pasta

<p align="right">7.21.2017</p>

<h1 align="center">food processor pasta dough</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>

### ingredients
- 3 eggs
- 1/2 tsp salt
- 2 cups all purpose flour
- 1 Tbsp olive oil

### instructions
1. Pulse salt and flour in a food processor. 
1. Add eggs and olive oil to bowl and process for 30-60 seconds.  The contents should come together into a large ball.  
If the dough isn't coming coming together add water 1 tbsp at a time and process again for 15 seconds.
1. Once you have a ball, plop the dough onto a cutting board and knead until the ball is relatively smooth and soft.  
This is typically a minute or two.
1. Cover the dough with plastic wrap and let rest for 30 minutes.  Once rested it is ready to be rolled into whatever style pasta you'd like

### notes
For a more decadent pasta, replace one whole egg with two yolks.
