<p align="right">12.31.2017</p>

<h1 align="center">miso rice bowl</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a> | 
</div>
<br>
# miso rice bowl
# miso rice bowl

### ingredients
- 3/4 cup of brown rice 
- 1/4 cup of wild rice
- 1-2 sweet potatoes; peeled and 3/4" cubed
- 1 large bundle of broccoli
- 2-4 tbsp neutral oil
- coarse or kosher salt
- freshly ground black pepper
- 1 tsp white sesame seeds
- 1 tsp black sesame seeds
- 1 recipe miso-tahini dressing

### instructions
1. Heat oven to 400F. Cook rice in a rice cooker on the brown setting. 
1. Toss sweet potatoes in a neutral oil and a sprinkle of salt.
1. Using one large or two smaller trays, spread out sweet potatoes and roast for 20 minutes, until browning underneath. 
Flip, toss, and add broccoli to the tray.  Drizzle with a little more neutral oil and a sprinkle of salt. Roast for 
another 10-20 minutes. Broccoli should be lightly charred at the edges and sweet potatoes should be browned and tender.
1. While vegetables are roasting, prepare the miso-tahini dressing.
1. Assemble bowls. Scoop rice into each bowl, pile on vegetables, and coat lightly with dressing. Sprinkle toasted 
sesame seeds on top.

### notes
Easily doubled. Equally delicious over wheat berries or farro.  Also good with a drizzle of sriracha.  
