# salt brine pickles

<p align="right">1.2.2020</p>

<h1 align="center">salt brine fermented pickles</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>

### ingredients
- 2 TB salt
- vegetables

### instructions
1. Stir 2 TB salt into a 1 quart mason jar until salt is dissolved. 
2. Add chopped vegetables to the mason jar. Turnips, beets, radishes, carrots are particularly tasty.
3. Optionally, add spices, particularly garlic, ginger, peppers (hot or sweet), and onions.
4. Cover the mason jar loosely with its lid. If possible, ensure that the vegetables are submerged with the brine: one easy way to do this is to fill a plastic bag with beans and place it on top of the vegetables and brine. Specialized tools also exist. If the vegetables are not completely covered, those that are exposed to the air can be removed before storage. 
5. Ferment between 2-3 days and 2-3 weeks, or longer. Refrigerate to store with a closed lid.

### notes
If possible, use filtered water, as chlorine in water may inhibit lactic acid fermentation. The ratio of 2 TB salt to 1 quart of water can be scaled up or down (i.e., for 1 gallon of water, use 8 TB [1/2 cup] of salt). Salt can be reduced to taste, especially when a longer time is used for the ferment. Especially in cooler weather, as little as 1 TB salt per quart of water may suffice. This technique works for any vegetable, though leafy greens are known to taste bitter with this method.
