<p align="right">12.31.2017</p>

<h1 align="center">turnip red lentil stew</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>
# turnip red lentil stew
# turnip red lentil stew

### ingredients
- 1 sweet onion; diced
- 4 garlic cloves; minced
- 1 bunch of small turnips (I like hakurei); washed, trimmed, and quartered or 4 large turnips; peeled and 1/2" dice
- 1 can tomato puree
- 4 cups vegetable broth and extra vegetable base concentrate
- 1 bunch chard (could substitute lacinato kale); washed, thick stems removed, and thinly sliced
- 1 cup red lentils; rinsed just before cooking
- 2 tbsp olive or neutral oil
- 1/2 tsp thyme (fresh or dried)
- 1/4 tsp dried sage (optional)
- pinch of red pepper flakes (optional)
- 2 shallots; cut in half lengthwise and thinly sliced (optional; see recipe)
- 1/4 cup neutral oil (optional; see recipe)
- 1 pinch salt (optional; see recipe)


### instructions
1. Heat pan on medium flame then add oil and onion. Cook until onion begins to soften then add garlic and cook until 
both are softened through - just sweating the veggies, no need to try to brown here. Add turnips and toss.  Add tomato 
sauce and veggie broth and stir to combine. If using large turnips, cook for 15 minutes to get out any bitterness.  
Add lentils and stir again. 
1. If making the optional crispy, caramelized shallots, add shallots and oil to a pan on medium low.  After a few 
minutes the shallots should be sizzling as they release their moisture.  Cook while stirring occasionally and continue 
with the stew steps below. About 20 minutes in the shallots should be turning golden. Remove them from the oil and 
spread out on a paper towel lined plate and sprinkle with salt.
1. Bring soup to a boil then reduce to a simmer and cook for about 20 minutes stirring occasionally. Around then the 
lentils will be a consistent color and texture though and will plump up to fill the pot all of the sudden. At this 
point stir in the herbs if you're using them and the greens and let cook for a couple minutes.
1. Taste the soup- if it lacks body, add vegetable broth base 1/2 tsp at a time, or maybe a pinch of salt if it just 
needs more seasoning.

### notes
Serve with a crack of pepper and/or a pinch of red pepper flakes.

