<p align="right">12.22.2019</p>

<h1 align="center">vegan pumpkin cholocate chip cookies</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>
# vegan pumpkin chocolate cookies
# vegan pumpkin chocolate cookies

### ingredients
- 1/2 cup coconut oil; solid (be sure it's not melted)
- 3/4 cups dark brown sugar; packed
- 1/2 cup granulated sugar
- 2 tsp vanilla extract
- 2 Tbsp maple syrup
- 2 Tbsp unsweetened coconut milk (almond or soy milk will also work)
- 2/3 can pumpkin puree (not pumpkin pie mix)
- 2 1/4 cups all-purpose flour; unpacked
- 1 tsp baking soda
- 1/2 tsp salt
- 2 tsp pumpkin pie spice (optional)
- 1/2 - 1 cup chocolate chips 
- coarse salt

### instructions
1. Preheat oven to 375F. Line a large baking sheet with parchment paper; set aside.
1. In the bowl of a stand mixer fitted with the paddle attachment, or in a large bowl using a handheld electric mixer, 
beat the coconut oil, both sugars, and vanilla on medium-speed until smooth; about 2 minutes. Add in the molasses, 
coconut milk and pumpkin puree and beat on low speed until well combined. Turn mixer off.
1. In a separate bowl combine the flour, baking soda, salt, and pumpkin pie spice; whisk well to combine.
1. Add the dry ingredients into the wet mixture and, with the mixer on low speed, beat until ingredients are combined. 
The batter will be very thick! Fold in 1 and 1/4 cups of the chocolate chips.
1. Scoop three tablespoon sized mounds of dough onto the prepared cookie sheet, leaving a few inches between each 
cookie. Bake for 9 to 10 minutes, or until the edges are golden and the centers are soft but set. Press remaining 
chocolate chips on top of warm cookies, and sprinkle with sea salt, if using. Cool cookies on the baking sheet for 30 
minutes before transferring them to a cooling rack.

### notes
Jess' creation and favorite desert. These are somewhere between a cookie and a muffin top.

