<p align="right">9.18.2018</p>

<h1 align="center">coconut baked oatmeal</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>
# coconut baked oatmeal
# coconut baked oatmeal

### ingredients
- 1 Tbsp coconut oil (or other neutral oil to grease baking pan)
- 3 ripe bananas 
- 2 eggs
- 1/3 cup shredded, unsweetened coconut
- 1/4 cup brown sugar
- 1 tsp vanilla extract 
- 1 tsp baking powder
- 1/2 tsp kosher salt 
- 1 can coconut milk 
- 2 1/4 cup rolled oats (not quick cooking)
- bluberries, strawberries, raspberries, blackberries; washed (optional)
- coconut whipped cream (optional)

### instructions
1. Preheat the oven to 375F (without convection) and melt coconut oil (or replacement) to grease baking dish.
1. Smash bananas in large mixing bowl. Combine all ingredients up to rolled oats and mix well.  Spoon in oats and 
stir to combine.
1. Bake for 45 minutes.  Remove and let cool for a couple minutes before digging in.  Optionally, top with fruit and 
coconut whipped cream.

### notes
Can be served warm or cold. Keeps for a few days in the fridge.
