<p align="right">4.11.2018</p>

<h1 align="center">jess bowl</h1>

<div align="center">
  <a href="#ingredients">ingredients</a> | 
  <a href="#instructions">instructions</a> | 
  <a href="#notes">notes</a>
</div>
<br>
# jess bowl
# jess bowl

### ingredients
- neutral oil
- 1 3/4 cup brown rice
- 1/4 cup wild rice; cooked
- 2 large sweet potatoes; 3/4" dice
- 2 delicata squash; cut into half moons
- 1 recipe miso braised greens
- 8 oz crimini mushrooms; stems removed and washed, cut in half
- 2 tbsp neutral oil
- kosher salt
- 1 avocado; sliced
- sriracha to taste
- toasted sesame oil to taste
- soy sauce or tamari to taste
- 1 tsp white sesame seeds
- 1 tsp black sesame seeds
- fried egg (optional)

### instructions
1. Cook rice in a rice cooker on brown setting or on the stove.
1. Heat oven to 400F. Peel sweet potatoes and cut into 3/4" cubes. Toss in a 1-2 Tbsp neutral oil with a 
sprinkle of salt. Cut off top of delicata squash, slice length-wise, scoop out inards, and slice into 1/2" wide 
half moons. Again, toss in a neutral oil with a sprinkle of salt. Using one large or two smaller trays, spread 
out sweet potatoes and delicata squash. Roast for 20 minutes, until browning underneath. Flip and toss. Roast for 
another 10-20 minutes. Sweet potatoes should be bronzed and tender and squash should be browning at edges. Toss 
chunks around one more time if it looks like they are cooking unevenly.
1. While potatoes and squash are cooking, heat a pan to medium-low heat. Add 2 Tbsp neutral oil and crimini mushrooms 
to the pan, cooking until tender. While mushrooms are cooking, prepare japanese braised greens. Jess prefers using 
lacinato kale for this specific recipe, as opposed to chard. Throw cooked mushrooms into the pan of greens, stir, and 
cook together on low for another minute. Remove from heat and set aside.
1. Prepare bowls. Before adding vegetables, mix a dash of toasted sesame oil into the cooked rice. Pile on vegetables 
and top with a fried egg (optional). Add tamari/soy sauce and siracha to taste.

### notes
Best rice bowl ever.  Rice can be cooked on a timer so that it can soak for longer, up to 12 hours. 
