name: Build & Deploy Site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4) Run your build script
      - name: Build site
        run: python build.py

      # 5) Deploy the resulting docs/ to your master/docs via gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # target your main branch instead of the default gh-pages branch:
          publish_branch: master
          # local folder to push:
          publish_dir: docs
          # remote path within publish_branch:
          destination_dir: docs
          # avoid infinite loops:
          commit_message: "Auto build & deploy site [skip ci]"
