name: pages build and deployment

on:
  push:
    branches: [ master ]          # change to main if needed

# minimum scopes deploy-pages needs
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
# ---------- BUILD ----------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # language tooling (allowed)
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Build site
        run: python build.py        # regenerates docs/

      # REQUIRED so the next step can resolve its dependencies
      - uses: actions/configure-pages@v3

      # upload the docs/ folder as the GitHub Pages artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs

# ---------- DEPLOY ----------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
